message("building ${main_name}.pdf")
execute_process(COMMAND pdflatex "${main_name}.tex")
file(SHA256 "${main_name}.pdf" hash)
while(1)
  message("building ${main_name}.pdf (sha=${hash}) again...")
  execute_process(COMMAND pdflatex "${main_name}.tex")
  file(SHA256 "${main_name}.pdf" new_hash)
  if(new_hash STREQUAL hash)
    break()
  endif()
  set(hash "${new_hash}")
endwhile()
