name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: cmake . && make
    - uses: actions/upload-artifact@master
      with:
        name: cv.pdf
        path: cv.pdf
